resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4b4457e75303ce352223b9723f7771fac6fe0600/snapshot.yaml

packages:
  - ./
  - test/

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3bb05f785ef6427a87af43517c561713e8314c94
    subdirs:
      - .
      - test

nix:
  packages:
    - zlib
