resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/7f8544ae9e162b6664f07093227edb148f1c8a5b/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test
  - specs/ledger/hs
  - specs/semantics/hs

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 7f8544ae9e162b6664f07093227edb148f1c8a5b
    subdirs:
      - .
      - test

  # - git: https://github.com/input-output-hk/cardano-chain
  #   commit: c14a65370cfd70c2c9a77003072e20113894f6c9
  #   subdirs:
  #     - binary
  #     - binary/test

  # - git: https://github.com/input-output-hk/cardano-chain
  #   commit: c14a65370cfd70c2c9a77003072e20113894f6c9
  #   subdirs:
  #     - crypto
  #     - crypto/test

  - git: https://github.com/input-output-hk/cardano-mainnet-mirror
    commit: 74ca63f8ad6b47beba2f565c73592cede63ce4b5

  - sequence-0.9.8
  - tasty-hedgehog-0.2.0.0

nix:
  shell-file: scripts/nix/stack-shell.nix
