resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4b4457e75303ce352223b9723f7771fac6fe0600/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: c219477a4313767d9786147008026d84afce2f12
    subdirs:
      - .
      - test

nix:
  shell-file: scripts/nix/stack-shell.nix
