resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4b4457e75303ce352223b9723f7771fac6fe0600/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 0889d18d3581026598b9268637475525064b76fe
    subdirs:
      - .
      - test

nix:
  shell-file: scripts/nix/stack-shell.nix
