resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d8091767addc1a51e11cb2f04392e4eb40e39b18/snapshot.yaml

packages:
  - .
  - test
  - crypto
  - crypto/test
  - validate-mainnet

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d8091767addc1a51e11cb2f04392e4eb40e39b18
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 5bca69f048c4d599c362d797ee8b036c118f77f4
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 30f2728662e782c50f2da1f66f4b3159e85c8ff1
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  - sequence-0.9.8
  - tasty-hedgehog-0.2.0.0
  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 4be5660c721cae4b001187ec614ef5cf4fad8fc7

  - time-units-1.0.0
  - ekg-0.4.0.15
  - ekg-json-0.1.0.6

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 00413dcad916a41cf392437199cfba7a2e2c76d7
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Needed for IOHK monitoring
  - libyaml-0.1.0.0

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 997fbb38b08dec14d225d064dac05b0a85f4ceae

nix:
  shell-file: scripts/nix/stack-shell.nix
