resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/f2802079ba2c07c4d408e3c0aa000fc363792398/snapshot.yaml

packages:
  - .
  - test
  - specs/ledger/hs
  - specs/semantics/hs

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: db5deaa1780b3a0811aaa4b8941037c5efa17105
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-chain
    commit: 4d9eec080374179bf15bf9c4fca09cc7d73e5f53
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-chain
    commit: 4d9eec080374179bf15bf9c4fca09cc7d73e5f53
    subdirs:
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-mainnet-mirror
    commit: 74ca63f8ad6b47beba2f565c73592cede63ce4b5

  - sequence-0.9.8

nix:
  shell-file: scripts/nix/stack-shell.nix
