resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/85fe2b8094b10e5f669423e0a8af327017cb0771/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 0bc8d7d419994c680f22e8c266652812eccd1f10
    subdirs:
      - .
      - test

nix:
  shell-file: scripts/nix/stack-shell.nix
