resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4b4457e75303ce352223b9723f7771fac6fe0600/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 0889d18d3581026598b9268637475525064b76fe
    subdirs:
      - .
      - test
  - git: https://github.com/well-typed/cborg # https://github.com/well-typed/cborg/pull/185
    # This adds the capability to extract byte offsets in decoders
    commit: 80fbe0ee5e67a5622e2cb9eaa9d8594a2214322d
    subdirs:
      - cborg


nix:
  shell-file: scripts/nix/stack-shell.nix
