resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/4b4457e75303ce352223b9723f7771fac6fe0600/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3793d79323f2e7c34711cba80e6b24d01937d8f5
    subdirs:
      - .
      - test

nix:
  shell-file: scripts/nix/stack-shell.nix
