resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/7f8544ae9e162b6664f07093227edb148f1c8a5b/snapshot.yaml

packages:
  - .
  - test
  - binary
  - binary/test
  - crypto
  - crypto/test
  - specs/ledger/hs
  - specs/semantics/hs

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 7f8544ae9e162b6664f07093227edb148f1c8a5b
    subdirs:
      - .
      - test
  - sequence-0.9.8
  - tasty-hedgehog-0.2.0.0

nix:
  shell-file: scripts/nix/stack-shell.nix
