resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/85fe2b8094b10e5f669423e0a8af327017cb0771/snapshot.yaml

packages:
  - .
  - test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: db5deaa1780b3a0811aaa4b8941037c5efa17105
    subdirs:
      - .
      - test

  - ../binary
  - ../binary/test

nix:
  packages:
    - openssl
    - zlib
